In [1]:
import numpy as np

In [2]:
arr1=np.array([0.5,3,30])   #一维数组
arr2=np.array([[1,2,3,4],[5,6,7,8]])   #二维数组
print(arr2)
print(arr1)
print(type(arr1))
print(type(arr2))

[[1 2 3 4]
 [5 6 7 8]]
[ 0.5  3.  30. ]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
arr1

array([ 0.5,  3. , 30. ])

In [4]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2[1][2]

7

In [6]:
print(arr1.shape)

(3,)


In [7]:
print(arr2.ndim)
print(arr2.dtype)
print(arr1.dtype)
print(arr2.shape)

2
int64
float64
(2, 4)


#数组特点

In [8]:
list1 = [0.3,0.5,3.5]
arr1 = np.array([0.3,0.5,3.5])

print(list1)
print(arr1)

print([i**2 for i in list1])
print(arr1**2)

[0.3, 0.5, 3.5]
[0.3 0.5 3.5]
[0.09, 0.25, 12.25]
[ 0.09  0.25 12.25]


In [9]:
arr3 = np.arange(0,10)
arr4 =np.arange(10)
arr5 = np.arange(0,1,0.1)
print(arr4)
print(arr3)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [10]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [11]:
arr6 =np.linspace(0,1,10)
print(arr6)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [12]:
arr7 = np.zeros([2,4,5])
print(arr7)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [19]:
arr8 = np.array([3,4,5],dtype=np.float64)
print(arr8)
print(arr8.dtype)
arr8[0]=1.2

print(np.int32(arr8))
print(arr8)

[3. 4. 5.]
float64
[1 4 5]
[1.2 4.  5. ]
